### PR TITLE
Updated fxos_addon_Status_Bar_Temperature

### PR DESCRIPTION
**Pull request by SunboX**

### CODE REVIEW

**Comment by mikehenrty** [comment]
Hi André, thanks for the Pull Request. We are deprecating Hackerplace in favor of just hosting add-ons in the Marketplace. So please submit your add-on there :)

Let me know if you would like some instructions on submitting to the Marketplace.

**Comment by SunboX** [comment]
Hi Michael,

I've already submitted it to the Marketplace for review, thanks. :smile: But I thought Hackerplace will stay alive until the add-on section in the Marketplace was rolled out. :smirk: 

Btw., I think I found a small issue. If I make a filter for the settings app like this:

``` json
{
  "matches": [ "app://settings.gaiamobile.org/index.html" ],
  "js": [ "settings.js" ]
}
```

It will show the name `Settings` under the `Affected Apps` section in the add-on details panel. But the `settings.js` add-on will not get applied to the settings app, because the settings app will get called with an empty hash `#` from the home screen. So to fix this, I have to change the filter to:

``` json
{
  "matches": [ "app://settings.gaiamobile.org/index.html*" ],
  "js": [ "settings.js" ]
}
```

But now the `Affected Apps` section in the add-on details panel does not show `Settings`any more. So to fix both of this, I have to define the filter like this:

``` json
{
  "matches": [ 
    "app://settings.gaiamobile.org/index.html",
    "app://settings.gaiamobile.org/index.html*"
  ],
  "js": [ "settings.js" ]
}
```

Now the name does appear and the `settings.js` get's applied. :smirk:

**Comment by mikehenrty** [comment]
Ahh, that's a bug. Please file :D

ʍ

**Comment by SunboX** [comment]
k, where do I file it? 
- Gaia::Settings
- Add-on SDK 
- ... ?

**Comment by mikehenrty** [comment]
Gaia::Settings is my guess. But you're right it could be Add-on SDK too.
Let's start with Settings.

Thanks!

ʍ

**Comment by SunboX** [comment]
done.
https://bugzilla.mozilla.org/show_bug.cgi?id=1218330

**Comment by anaran** [comment]
The `Add-on SDK` is about jetpack add-ons which are not supported on Firefox OS AFAIK.

See
https://github.com/mozilla/addon-sdk
and
https://github.com/mozilla-jetpack/jpm
for the tooling to build such add-ons.

Firefox Add-ons are also on their way to migrate to
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

Of the examples at
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Examples
only
borderify (sort of)
and
page-to-extension-messaging
currently work in Nightly Firefox OS, installed from Desktop Firefox via WebIDE.

**Pull request closed without merging**
