### PR TITLE
Updated Status Bar Temperature Addon

### PR DESCRIPTION
**Pull request by SunboX**

### CODE REVIEW

**Comment by mikehenrty** [comment]
Awesome @SunboX !!
How do I open the settings panel for this add-on?

**Comment by SunboX** [comment]
Just enable the addon and then visit the addon settings again. It will check the "addon-details" card in the settings app and inject the custom settings there. I've proposed a enhancement for doing stuff like this here: https://bugzilla.mozilla.org/show_bug.cgi?id=1185563

**Comment by mikehenrty** [comment]
@SunboX ah I see. You need to push your latest changes to your gh-pages branch. The manifest at https://sunbox.github.io/mozweekend_AddOn_Demo/manifest.webapp doesn't include settings app injection at the moment.

**Comment by SunboX** [comment]
oh ... that's true. Forgot about that :blush: Thanks a lot!

**Comment by SunboX** [comment]
... merged.

**Comment by mikehenrty** [comment]
You removed package_path from your manifest.webapp. Please put that back.

https://github.com/SunboX/mozweekend_AddOn_Demo/commit/c4eb846cb383df5a851f088b8b7444375bcf3ca4#diff-cce7d5386ce0d127e7ed7c23fe13b4caL26

**Comment by SunboX** [comment]
Oh, ok ... didn't really know that this is required. Re-added it. Thanks again!

**Comment by mikehenrty** [comment]
Looking good! Thanks!

**Pull request merged**
