### PR TITLE
Update responsive-irccloud and make it forward compatible.

### PR DESCRIPTION
**Pull request by eeejay**
Changelog!
1. Responsivize enterprise login page.
2. Make a splash screen.
3. dialog improvements.
4. v2 addon api support

### CODE REVIEW

**Comment by mikehenrty** [comment]
You need to remove the `url` field from the `developer` item in your `update.webapp`. Otherwise you get a MANIFEST_MISMATCH error when trying to install :/

**Comment by eeejay** [comment]
Updated!

**Comment by mikehenrty** [comment]
You're missing a comma after the homepage_url field in your manifest.json.

Are you able to test install the new add-ons using webIDE? Some people have been reporting issues with it.

**Comment by eeejay** [comment]
Nope! That is why I am missing stupid syntax issues :) I don't think my foxfooding device even supports the new format (right?)

**Comment by mikehenrty** [comment]
You're right it doesn't!

You should be able to install the new format to a flame on a nightly build. I'm going to test installing a new add-on in webIDE right now.

**Comment by mikehenrty** [comment]
Hi @eeejay, sorry for the delay here. 

You're missing a comma in your manifest.json. Right now it's not valid json.

**Comment by eeejay** [comment]
Yeah, I was having a hard time actually testing this on a device. Once I do, I'll resubmit.

**Comment by eeejay** [comment]
Looks like I am blocked by bug 1211709.

**Comment by mikehenrty** [comment]
Hi Eitan, we are deprecating Hackerplace in favor of Marketplace. Please submit your updated add-on there. Let me know if you have any questions about how to do so.

**Pull request closed without merging**
