### PR TITLE
Added BLE Explorer App.

### PR DESCRIPTION
**Pull request by elin-moco**
This is a certified app, is it OK to specify "type": "packaged" in this file?

### CODE REVIEW

**Comment by mikehenrty** [comment]
@elin-moco Thanks for the app Eddie! The launch_path right now is incorrect is you want it to be hosted. It needs to be relative, since the index file will not reside at the github pages root. See [1] for an example.

You might just consider making this a packaged app. That way a user wouldn't have to be online to use this.

1.) https://fxos.github.io/dialer/dist/app/manifest.webapp

**Comment by elin-moco** [comment]
Thanks! I've updated manifest.webapp and package.zip

**Comment by mikehenrty** [comment]
Just for the record, right now the app is hosted rather than packaged. The reason it is hosted is because you have a launch_path in your webapp.manifest. To make it packaged you specify a package_path instead of launch_path (so right now the package.zip will be unused). Don't worry though, I'll update the "type" to say "hosted" in directory, and we'll just go with the hosted version.

**Comment by elin-moco** [comment]
Cool, thank you!
I was so confused about how to properly fill in the manifest...
will try it with next update.

**Pull request merged**
