### PR TITLE
Bug 1186624 - Migrating addon to new format r=mhenretty

### PR DESCRIPTION
**Pull request by CodingFree**

### CODE REVIEW

**Comment by mikehenrty** [comment]
Instead of `developer` in your `manifest.json`, you need the `author` field:

```
"author": "Adrian Crespo, Giovanny Gongora",
...
```

https://developer.chrome.com/extensions/manifest

**Comment by CodingFree** [comment]
Done, @mikehenrty, thanks! :)

**Comment by mikehenrty** [comment]
From your server, you must serve the `update.webapp` with one of the following content types:

application/x-web-app-manifest+json
application/manifest+json

**Comment by CodingFree** [comment]
I am really sorry. It was fixed and now it's working, at last.

**Comment by mikehenrty** [comment]
nice work!

**Pull request merged**
