### PR TITLE
Add tab switcher shortcut addon

### PR DESCRIPTION
**Pull request by callahad**
Add-on for the the browser that puts a switch-tabs button in the top bar.

### CODE REVIEW

**Comment by mikehenrty** [comment]
Awesome Dan! Thanks for submitting this.

Your manifest at `https://callahad.github.io/fxos-tabswitcher-addon/manifest.webapp` is missing the package_path property. Without this, hackerplace won't be able to install your app. You need to zip up your js file and icon, and then put that zip at the package path. See https://github.com/mikehenrty/fxos-cracked/tree/gh-pages.

**Comment by mikehenrty** [comment]
@callahad Do you think we should add this step to the README of hackerplace?

**Comment by callahad** [comment]
Hah, whoops. Pushes fine from WebIDE. Fixing now. A reminder in the README would be handy.

**Comment by callahad** [comment]
Added a package_path and force pushed to my branch. r? @mikehenrty

**Comment by callahad** [comment]
Oh, I'm a doofus. Fixing one typo and re-pushing real quick.

**Pull request merged**
