### PR TITLE
Add Minimal Home Button addon

### PR DESCRIPTION
**Pull request by hobinjk**

### CODE REVIEW

**Comment by mikehenrty** [comment]
Thanks for the add-on James!!

It looks like the zip package on your gh-pages branch has the wrong javascript file in it. Instead of `minimal-home-button.js` in there, I see `always-fullscreen.js` which means your add-on is not loading anything currently. Please fix and @ flag me for review again :)

**Comment by hobinjk** [comment]
Fixed! I forgot to update the Makefile and `zip` never said anything because it's the worst.
@mikehenrty

**Comment by mikehenrty** [comment]
Thanks James, this is really cool!

I've you're interested in expanding on this add-on, we can make the app window extend to the full screen and have the SHB just hover above it. I can help if your interested. In any case, I'm putting this in now.

**Comment by hobinjk** [comment]
@mikehenrty What exactly do you have in mind? In my experience after restarting with this addon it properly gets the app windows to extend all the way to the bottom

**Comment by mikehenrty** [comment]
Hrmm, maybe I didn't restart the homescreen after installing your add-on? I'm not sure.

**Comment by mikehenrty** [comment]
I also remember the homebar being transparent, and now it's looks black, so
maybe I just had a bad install.

Landscape mode still looks a little funky (the right side of the screen
just shows a missing bar). Anyway, just things to iron out if you have time.

ʍ

**Comment by hobinjk** [comment]
All of those work on my device. My guess would be that some of the other SHB addons interfere with it.

**Comment by mikehenrty** [comment]
Yup, I bet you're right.

ʍ

**Pull request merged**
