### PR TITLE
Update readme to point to apps.json

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

**Comment by mikehenrty** [comment]
@DouglasSherk r?

**Comment by DouglasSherk** [comment]
r+

**Comment by DouglasSherk** [comment]
I doubt many people will actually be following these instructions, though.

**Comment by mikehenrty** [comment]
I've been pointing people at this. We have 3 contribs right now.

ʍ

**Comment by DouglasSherk** [comment]
Cool, I'm happy to be wrong then.

**Pull request merged**
